common:
  # ip 代理池
  proxy_pool:
    # 是否启用 true/false
    enable: false
    # ip池地址，参考 https://github.com/jhao104/proxy_pool
    proxy_pool_url: http://ip:port
  # 推送通道
  push_channel:
    # 是否在项目启动时，给各通道发送一条测试消息 true/false
    send_test_msg_when_start: true

query_task:
  # 任务名称，可自定义
  - name: 任务_bilibili
    # 是否启用 true/false
    enable: true
    # 任务类型，bilibili/weibo/xhs/douyin
    type: bilibili
    # 查询间隔，单位秒，不建议设置太频繁
    intervals_second: 60
    # 查询开始时间，格式 HH:mm
    begin_time: "00:00"
    # 查询结束时间，格式 HH:mm
    end_time: "23:59"
    # 推送通道名称，对应 push_channel 中的 name
    target_push_name_list:
      - 推送通道_Bark
    # 是否启用动态检测 true/false
    enable_dynamic_check: false
    # 是否启用直播检测 true/false
    enable_living_check: true
    # 用户 uid 列表，参考 https://space.bilibili.com/1795147802
    uid_list:
      - 406986743
      - 22902192
    # 如果请求提示 -352, 可以填入下面两项之一, 建议使用 payload 自动获取buvid3
    # cookie，可以一定程度防ban，建议用小号的，貌似无痕窗口不登录时拿到的cookie也能用，优先级高于自动获取buvid3
    cookie: ""
    # 浏览器指纹，取自于 /x/internal/gaia-gateway/ExClimbWuzhi 接口的body，需要填入的是payload参数的value，用于自动获取并激活buvid3
    payload: {"5062":1719628336643,"39c8":"333.1365.fp.risk","920b":"0","df35":"C7EF01D2-3E1E-5C8D-219D-A87B6E638A4B45613infoc","03bf":"https://t.bilibili.com/","3c43":{"2673":0,"5766":30,"6527":0,"7003":1,"807e":1,"b8ce":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36","641c":0,"07a4":"en","1c57":8,"0bd0":8,"748e":[800,1280],"d61f":[775,1280],"fc9d":-60,"6aa9":"Europe/London","75b8":1,"3b21":1,"8a1c":0,"d52f":"not available","adca":"MacIntel","80c9":[["PDF Viewer","Portable Document Format",[["application/pdf","pdf"],["text/pdf","pdf"]]],["Chrome PDF Viewer","Portable Document Format",[["application/pdf","pdf"],["text/pdf","pdf"]]],["Chromium PDF Viewer","Portable Document Format",[["application/pdf","pdf"],["text/pdf","pdf"]]],["Microsoft Edge PDF Viewer","Portable Document Format",[["application/pdf","pdf"],["text/pdf","pdf"]]],["WebKit built-in PDF","Portable Document Format",[["application/pdf","pdf"],["text/pdf","pdf"]]]],"13ab":"7wAAAABJRU5ErkJggg==","bfe9":"mgQDYKAKxsrCZRFLCvwP8Bqjz+poigxo4AAAAASUVORK5CYII=","a3c1":["extensions:ANGLE_instanced_arrays;EXT_blend_minmax;EXT_clip_control;EXT_color_buffer_half_float;EXT_depth_clamp;EXT_disjoint_timer_query;EXT_float_blend;EXT_frag_depth;EXT_polygon_offset_clamp;EXT_shader_texture_lod;EXT_texture_compression_bptc;EXT_texture_compression_rgtc;EXT_texture_filter_anisotropic;EXT_texture_mirror_clamp_to_edge;EXT_sRGB;KHR_parallel_shader_compile;OES_element_index_uint;OES_fbo_render_mipmap;OES_standard_derivatives;OES_texture_float;OES_texture_float_linear;OES_texture_half_float;OES_texture_half_float_linear;OES_vertex_array_object;WEBGL_blend_func_extended;WEBGL_color_buffer_float;WEBGL_compressed_texture_astc;WEBGL_compressed_texture_etc;WEBGL_compressed_texture_etc1;WEBGL_compressed_texture_pvrtc;WEBGL_compressed_texture_s3tc;WEBGL_compressed_texture_s3tc_srgb;WEBGL_debug_renderer_info;WEBGL_debug_shaders;WEBGL_depth_texture;WEBGL_draw_buffers;WEBGL_lose_context;WEBGL_multi_draw;WEBGL_polygon_mode","webgl aliased line width range:[1, 1]","webgl aliased point size range:[1, 511]","webgl alpha bits:8","webgl antialiasing:yes","webgl blue bits:8","webgl depth bits:24","webgl green bits:8","webgl max anisotropy:16","webgl max combined texture image units:32","webgl max cube map texture size:16384","webgl max fragment uniform vectors:1024","webgl max render buffer size:16384","webgl max texture image units:16","webgl max texture size:16384","webgl max varying vectors:30","webgl max vertex attribs:16","webgl max vertex texture image units:16","webgl max vertex uniform vectors:1024","webgl max viewport dims:[16384, 16384]","webgl red bits:8","webgl renderer:WebKit WebGL","webgl shading language version:WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)","webgl stencil bits:0","webgl vendor:WebKit","webgl version:WebGL 1.0 (OpenGL ES 2.0 Chromium)","webgl unmasked vendor:Google Inc. (Apple)","webgl unmasked renderer:ANGLE (Apple, ANGLE Metal Renderer: Apple M1, Unspecified Version)","webgl vertex shader high float precision:23","webgl vertex shader high float precision rangeMin:127","webgl vertex shader high float precision rangeMax:127","webgl vertex shader medium float precision:23","webgl vertex shader medium float precision rangeMin:127","webgl vertex shader medium float precision rangeMax:127","webgl vertex shader low float precision:23","webgl vertex shader low float precision rangeMin:127","webgl vertex shader low float precision rangeMax:127","webgl fragment shader high float precision:23","webgl fragment shader high float precision rangeMin:127","webgl fragment shader high float precision rangeMax:127","webgl fragment shader medium float precision:23","webgl fragment shader medium float precision rangeMin:127","webgl fragment shader medium float precision rangeMax:127","webgl fragment shader low float precision:23","webgl fragment shader low float precision rangeMin:127","webgl fragment shader low float precision rangeMax:127","webgl vertex shader high int precision:0","webgl vertex shader high int precision rangeMin:31","webgl vertex shader high int precision rangeMax:30","webgl vertex shader medium int precision:0","webgl vertex shader medium int precision rangeMin:31","webgl vertex shader medium int precision rangeMax:30","webgl vertex shader low int precision:0","webgl vertex shader low int precision rangeMin:31","webgl vertex shader low int precision rangeMax:30","webgl fragment shader high int precision:0","webgl fragment shader high int precision rangeMin:31","webgl fragment shader high int precision rangeMax:30","webgl fragment shader medium int precision:0","webgl fragment shader medium int precision rangeMin:31","webgl fragment shader medium int precision rangeMax:30","webgl fragment shader low int precision:0","webgl fragment shader low int precision rangeMin:31","webgl fragment shader low int precision rangeMax:30"],"6bc5":"Google Inc. (Apple)~ANGLE (Apple, ANGLE Metal Renderer: Apple M1, Unspecified Version)","ed31":0,"72bd":0,"097b":0,"52cd":[0,0,0],"a658":["Andale Mono","Arial","Arial Black","Arial Hebrew","Arial Narrow","Arial Rounded MT Bold","Arial Unicode MS","Comic Sans MS","Courier","Courier New","Geneva","Georgia","Helvetica","Helvetica Neue","Impact","LUCIDA GRANDE","Microsoft Sans Serif","Monaco","Palatino","Tahoma","Times","Times New Roman","Trebuchet MS","Verdana","Wingdings","Wingdings 2","Wingdings 3"],"d02f":"124.04346607114712"}}
  - name: 任务_douyin
    enable: true
    type: douyin
    intervals_second: 30
    begin_time: "00:00"
    end_time: "23:59"
    target_push_name_list:
      - 推送通道_Bark
    enable_dynamic_check: false
    # 签名服务器url，参考 https://github.com/coder-fly/douyin-signature
    signature_server_url: http://ip:port
    # 用户名列表，必填（接口现在不返回作者信息了，重新获取还挺麻烦的，自己填上凑合用先）
    username_list:
      # - 大蛇丸
    # 作者sec_uid列表，参考 https://www.douyin.com/user/MS4wLjABAAAA5ZrIrbgva_HMeHuNn64goOD2XYnk4ItSypgRHlbSh1c
    sec_uid_list:
      # - MS4wLjABAAAA_5ttsDg-sAePrNQILFlVxwU8m0Srn28FPnM6oMGplZE
    enable_living_check: true
    # 抖音号列表，用于检测开播状态，如果不开启直播检测可以不填，现已支持纯数字的抖音号
    douyin_id_list:
      - 29879823171
  - name: 任务_douyu
    enable: true
    type: douyu
    intervals_second: 300
    begin_time: "00:00"
    end_time: "23:59"
    target_push_name_list:
      - 推送通道_Bark
    enable_living_check: true
    # 直播间号列表，用于检测开播状态，如果不开启直播检测可以不填
    room_id_list:
      - 12306
      - 52
      - 2561707

push_channel:
  # 通道名称，唯一，可自定义不要纯数字，对应 query_task 中的 target_push_name_list
  - name: 推送通道_Bark
    enable: true
    type: bark
    # iOS 设备专用，Bark app 的key，如果启动该推送则必填
    key: ELV6WywhCobjUuxTojNuzL
